# coding=utf-8

"""Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

def creattrinum(n):
	sum = 0
	for i in range(n+1):
		sum += i
	return sum

def divisors(n):
	divisors = [1, n]
	limit = int(n**0.5)+1
	for i in range(2, limit):
		if not i in divisors:
			if n%i==0:
				divisors.append(i)
				if not n/i in divisors: divisors.append(n/i)
	divisors.sort()
	print n, len(divisors)
	return len(divisors)
i =1
while True:
	x = creattrinum(i)
	if divisors(x)>500: break
	i+=1

	"""N = p1^a1 ( p2^a2 ( p3^a3 ( ...
where pn is a distinct prime number, and an is its exponent.
For example, 28 = 2^2( 7^1
Furthermore, the number of divisors D(N) of any integer N can be computed from:
D(N) = (a1+1) ( (a2+1) ( (a3+1) ( ...
an being the exponents of the distinct prime numbers which are factors of N """




